"""Added unique contsraint to short

Revision ID: 5c34faa83767
Revises: 
Create Date: 2022-08-31 13:20:52.337669

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5c34faa83767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'URL_map', ['short'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'URL_map', type_='unique')
    # ### end Alembic commands ###
